version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: multiverse_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./storage/www/:/var/www/:ro
      - ./storage/nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/errors/:/etc/nginx/errors/
    networks:
      - multiverse

  mysql:
    image: mysql:latest
    container_name: multiverse_mysql
    restart: unless-stopped
    env_file:
      - config/mysql.env
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    networks:
      - multiverse
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p ${DB_PASSWORD:-multiverse}" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: multiverse_phpmyadmin
    restart: unless-stopped
    links:
      - "mysql:db"
    networks:
      - multiverse
    depends_on:
      - mysql

  file_browser:
    image: filebrowser/filebrowser:latest
    container_name: multiverse_file_browser
    restart: unless-stopped
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
    volumes:
      - ./storage:/srv
    networks:
      - multiverse

networks:
  multiverse:
    name: multiverse
    driver: bridge
